runtime: nodejs18

handlers:
  # serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  REACT_APP_BASE_URL: "https://movie-time-frontend-tare392815.uw.r.appspot.com"
  REACT_APP_API_BASE_URL: "https://movie-time-backend-392813.uw.r.appspot.com"
  REACT_APP_GOOGLE_CLIENT_ID: "936756793185-2rj7mpved22eehd0lahrcdu2csl0vmie.apps.googleusercontent.com"
  REACT_APP_GOOGLE_CLIENT_SECRET: "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"
